#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/doily/parser.y".
#

require 'racc/parser'


require 'strscan'

module Doily

  class Parser < Racc::Parser

module_eval <<'..end lib/doily/parser.y modeval..id2752ca002a', 'lib/doily/parser.y', 57

  def self.function(string)
    new.parse(string)
  end

  def parse(string)
    @tokens = []
    scanner = StringScanner.new(string)

    until scanner.empty?
      case
			when scanner.scan(/\s+/)
				# ignore space
      when m = scanner.scan(/function/)
        @tokens.push [:FUNCTION, m]
      when m = scanner.scan(/if/)
        @tokens.push [:IF, m]
      when m = scanner.scan(/[(){},\.]/)
        @tokens.push [m, m]
      when m = scanner.scan(/==|</)
        @tokens.push [:OPERATOR, m]
      when m = scanner.scan(/[a-zA-Z]+/)
        @tokens.push [:IDENTIFIER, m]
      when m = scanner.scan(/"([^"])*"/)
        @tokens.push [:STRING_LITERAL, m]
      when m = scanner.scan(/\d+/)
        @tokens.push [:INTEGER_LITERAL, m]
      else
        raise ParseError.new(scanner)
      end
    end

    @tokens.push [false, false]
    do_parse
  end

  def next_token
    @tokens.shift
  end
..end lib/doily/parser.y modeval..id2752ca002a

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 15, :_reduce_none,
 7, 16, :_reduce_2,
 0, 17, :_reduce_3,
 1, 17, :_reduce_4,
 3, 17, :_reduce_5,
 0, 18, :_reduce_6,
 1, 18, :_reduce_7,
 1, 19, :_reduce_none,
 1, 19, :_reduce_none,
 1, 19, :_reduce_none,
 1, 20, :_reduce_11,
 1, 20, :_reduce_12,
 1, 20, :_reduce_13,
 3, 20, :_reduce_14,
 4, 20, :_reduce_15,
 0, 23, :_reduce_16,
 1, 23, :_reduce_17,
 3, 23, :_reduce_18,
 3, 21, :_reduce_19,
 7, 22, :_reduce_20 ]

racc_reduce_n = 21

racc_shift_n = 39

racc_action_table = [
    25,    26,    26,    15,    16,    17,    24,    24,    14,    15,
    16,    17,    14,    15,    16,    17,    14,    15,    16,    17,
    14,    15,    16,    17,    14,    15,    16,    17,     1,     6,
    22,    23,    12,    10,    28,     9,     8,    32,     6,    33,
    34,    35,     5,     4,    38 ]

racc_action_check = [
    20,    20,    29,    25,    25,    25,    20,    29,    26,    26,
    26,    26,    35,    35,    35,    35,    34,    34,    34,    34,
    22,    22,    22,    22,    12,    12,    12,    12,     0,     9,
    14,    18,    10,     7,    24,     6,     5,    27,     4,    30,
    31,    32,     2,     1,    37 ]

racc_action_pointer = [
    26,    35,    42,   nil,    34,    36,    23,    24,   nil,    25,
    22,   nil,    21,   nil,    22,   nil,   nil,   nil,    20,   nil,
    -7,   nil,    17,   nil,    30,    -1,     5,    28,   nil,    -6,
    30,    28,    31,   nil,    13,     9,   nil,    33,   nil ]

racc_action_default = [
   -21,   -21,   -21,    -1,    -3,   -21,    -4,   -21,    39,    -3,
   -21,    -5,    -6,   -10,   -21,   -11,   -13,   -12,   -21,    -7,
    -8,    -9,   -21,    -2,   -21,   -21,   -16,   -21,   -14,   -19,
   -21,   -17,   -21,   -15,   -16,    -6,   -18,   -21,   -20 ]

racc_goto_table = [
    18,    27,    30,     7,    29,    31,     3,     2,    11,   nil,
    36,   nil,   nil,    31,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    37 ]

racc_goto_check = [
     4,     5,     9,     3,     6,     5,     2,     1,     3,   nil,
     9,   nil,   nil,     5,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     4 ]

racc_goto_pointer = [
   nil,     7,     6,    -1,   -12,   -21,   -21,   nil,   nil,   -24 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,    19,    20,    21,    13,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :FUNCTION => 2,
 :IF => 3,
 :IDENTIFIER => 4,
 :STRING_LITERAL => 5,
 :INTEGER_LITERAL => 6,
 :OPERATOR => 7,
 "(" => 8,
 ")" => 9,
 "{" => 10,
 "}" => 11,
 "," => 12,
 "." => 13 }

racc_use_result_var = true

racc_nt_base = 14

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'FUNCTION',
'IF',
'IDENTIFIER',
'STRING_LITERAL',
'INTEGER_LITERAL',
'OPERATOR',
'"("',
'")"',
'"{"',
'"}"',
'","',
'"."',
'$start',
'target',
'function_definition',
'argument_name_list',
'expression_list',
'expression',
'reference',
'binary_expression',
'if_statement',
'argument_list']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

module_eval <<'.,.,', 'lib/doily/parser.y', 10
  def _reduce_2( val, _values, result )
 result = Function.new(val[2], val[5])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 14
  def _reduce_3( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 15
  def _reduce_4( val, _values, result )
 result = [val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 16
  def _reduce_5( val, _values, result )
 result = [val[0]] + val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 21
  def _reduce_6( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 22
  def _reduce_7( val, _values, result )
 result = [val[0]]
   result
  end
.,.,

 # reduce 8 omitted

 # reduce 9 omitted

 # reduce 10 omitted

module_eval <<'.,.,', 'lib/doily/parser.y', 32
  def _reduce_11( val, _values, result )
 result = Reference.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 33
  def _reduce_12( val, _values, result )
 result = Literal.new(val[0].to_i)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 34
  def _reduce_13( val, _values, result )
 result = Literal.new(eval(val[0]))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 35
  def _reduce_14( val, _values, result )
 result = Access.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 36
  def _reduce_15( val, _values, result )
 result = Call.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 40
  def _reduce_16( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 41
  def _reduce_17( val, _values, result )
 result = [val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 42
  def _reduce_18( val, _values, result )
 result = [val[0]] + val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 46
  def _reduce_19( val, _values, result )
 result = Call.new(Access.new(val[0], val[1]), [val[2]])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 50
  def _reduce_20( val, _values, result )
 result = Conditional.new(val[2], val[5])
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

  end   # class Parser

end   # module Doily
