#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/doily/parser.y".
#

require 'racc/parser'


require 'strscan'

module Doily

  class Parser < Racc::Parser

module_eval <<'..end lib/doily/parser.y modeval..idf2d78fa25d', 'lib/doily/parser.y', 62

  def self.function(string)
    new.parse(string)
  end

  def parse(string)
    @tokens = []
    scanner = StringScanner.new(string)

    until scanner.empty?
      case
			when scanner.scan(/\s+/)
				# ignore space
      when m = scanner.scan(/function/)
        @tokens.push [:FUNCTION, m]
      when m = scanner.scan(/if/)
        @tokens.push [:IF, m]
      when m = scanner.scan(/var/)
        @tokens.push [:VAR, m]
      when m = scanner.scan(/==|</)
        @tokens.push [:BINARY_OPERATOR, m]
      when m = scanner.scan(/[(){},\.;=]/)
        @tokens.push [m, m]
      when m = scanner.scan(/[a-zA-Z]+/)
        @tokens.push [:IDENTIFIER, m]
      when m = scanner.scan(/"([^"])*"/)
        @tokens.push [:STRING_LITERAL, m]
      when m = scanner.scan(/\d+/)
        @tokens.push [:INTEGER_LITERAL, m]
      else
        raise ParseError.new(scanner)
      end
    end

    @tokens.push [false, false]
    do_parse
  end

  def next_token
    @tokens.shift
  end
..end lib/doily/parser.y modeval..idf2d78fa25d

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 18, :_reduce_none,
 7, 19, :_reduce_2,
 0, 20, :_reduce_3,
 1, 20, :_reduce_4,
 3, 20, :_reduce_5,
 0, 21, :_reduce_6,
 1, 21, :_reduce_7,
 3, 21, :_reduce_8,
 1, 22, :_reduce_none,
 1, 22, :_reduce_none,
 1, 22, :_reduce_none,
 1, 22, :_reduce_none,
 1, 23, :_reduce_13,
 1, 23, :_reduce_14,
 1, 23, :_reduce_15,
 3, 23, :_reduce_16,
 4, 23, :_reduce_17,
 0, 27, :_reduce_18,
 1, 27, :_reduce_19,
 3, 27, :_reduce_20,
 4, 24, :_reduce_21,
 3, 25, :_reduce_22,
 7, 26, :_reduce_23 ]

racc_reduce_n = 24

racc_shift_n = 46

racc_action_table = [
    26,    27,    27,    27,    20,    21,    22,    25,    25,    25,
    16,    18,    20,    21,    22,    16,    18,    20,    21,    22,
    16,    18,    20,    21,    22,    16,    18,    20,    21,    22,
    16,    18,    20,    21,    22,    16,    18,    20,    21,    22,
    20,    21,    22,     1,    28,    29,    30,    24,    32,    12,
     6,    10,    37,     9,    38,    39,    40,     8,     6,    43,
     5,     4,    45 ]

racc_action_check = [
    14,    14,    41,    33,    26,    26,    26,    14,    41,    33,
    38,    38,    38,    38,    38,    24,    24,    24,    24,    24,
    43,    43,    43,    43,    43,    28,    28,    28,    28,    28,
    12,    12,    12,    12,    12,    27,    27,    27,    27,    27,
    37,    37,    37,     0,    16,    18,    23,    13,    25,    10,
     9,     7,    29,     6,    34,    35,    36,     5,     4,    40,
     2,     1,    44 ]

racc_action_pointer = [
    41,    52,    60,   nil,    53,    57,    40,    41,   nil,    45,
    38,   nil,    27,    33,    -8,   nil,    35,   nil,    40,   nil,
   nil,   nil,   nil,    34,    12,    43,    -1,    32,    22,    36,
   nil,   nil,   nil,    -6,    41,    45,    46,    35,     7,   nil,
    48,    -7,   nil,    17,    50,   nil ]

racc_action_default = [
   -24,   -24,   -24,    -1,    -3,   -24,    -4,   -24,    46,    -3,
   -24,    -5,    -6,    -7,    -9,   -10,   -24,   -11,   -24,   -12,
   -13,   -15,   -14,   -24,    -6,   -24,   -24,   -18,   -24,   -24,
    -2,    -8,   -16,   -22,   -19,   -24,   -24,   -24,   -18,   -17,
   -24,   -21,   -20,    -6,   -24,   -23 ]

racc_goto_table = [
    23,     7,    33,    34,    36,    35,    11,     3,     2,   nil,
   nil,   nil,    31,    41,    34,   nil,    42,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    44 ]

racc_goto_check = [
     4,     3,     6,     5,     5,    10,     3,     2,     1,   nil,
   nil,   nil,     4,     6,     5,   nil,    10,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     4 ]

racc_goto_pointer = [
   nil,     8,     7,    -3,   -12,   -24,   -24,   nil,   nil,   nil,
   -22 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,    13,    14,    15,    17,    19,
   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :FUNCTION => 2,
 :IF => 3,
 :VAR => 4,
 :IDENTIFIER => 5,
 :STRING_LITERAL => 6,
 :INTEGER_LITERAL => 7,
 :BINARY_OPERATOR => 8,
 "(" => 9,
 ")" => 10,
 "{" => 11,
 "}" => 12,
 "," => 13,
 ";" => 14,
 "." => 15,
 "=" => 16 }

racc_use_result_var = true

racc_nt_base = 17

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'FUNCTION',
'IF',
'VAR',
'IDENTIFIER',
'STRING_LITERAL',
'INTEGER_LITERAL',
'BINARY_OPERATOR',
'"("',
'")"',
'"{"',
'"}"',
'","',
'";"',
'"."',
'"="',
'$start',
'target',
'function_definition',
'argument_name_list',
'expression_list',
'expression',
'reference',
'assignment_expression',
'binary_expression',
'if_expression',
'argument_list']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

module_eval <<'.,.,', 'lib/doily/parser.y', 10
  def _reduce_2( val, _values, result )
 result = Function.new(val[2], val[5])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 14
  def _reduce_3( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 15
  def _reduce_4( val, _values, result )
 result = [val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 16
  def _reduce_5( val, _values, result )
 result = [val[0]] + val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 20
  def _reduce_6( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 21
  def _reduce_7( val, _values, result )
 result = [val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 22
  def _reduce_8( val, _values, result )
 result = [val[0]] + val[2]
   result
  end
.,.,

 # reduce 9 omitted

 # reduce 10 omitted

 # reduce 11 omitted

 # reduce 12 omitted

module_eval <<'.,.,', 'lib/doily/parser.y', 33
  def _reduce_13( val, _values, result )
 result = Reference.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 34
  def _reduce_14( val, _values, result )
 result = Literal.new(val[0].to_i)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 35
  def _reduce_15( val, _values, result )
 result = Literal.new(eval(val[0]))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 36
  def _reduce_16( val, _values, result )
 result = Access.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 37
  def _reduce_17( val, _values, result )
 result = Call.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 41
  def _reduce_18( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 42
  def _reduce_19( val, _values, result )
 result = [val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 43
  def _reduce_20( val, _values, result )
 result = [val[0]] + val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 47
  def _reduce_21( val, _values, result )
 result = Assignment.new(val[1], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 51
  def _reduce_22( val, _values, result )
 result = Call.new(Access.new(val[0], val[1]), [val[2]])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/doily/parser.y', 55
  def _reduce_23( val, _values, result )
 result = Conditional.new(val[2], val[5])
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

  end   # class Parser

end   # module Doily
